spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
